Cadastro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CadastroCliente.urls'))
]

CadastroCliente/urls.py
from django.urls import path
from CadastroCliente import views

urlpatterns = [
    path('', views.index, name='index'),
    path('clientes', views.listar_cliente, name='clientes'),
    path('profissoes', views.listar_profissoes, name='profissoes'),
    path('cliente/<int:id>', views.detalhar_cliente, name='detalhar')

]

CadastroCliente/models.py
from django.db import models

# Create your models here.
class Profissoes(models.Model):
    nome = models.CharField(max_length=30)

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = 'Profissoes'

class Interesse(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self): 
        return self.nome

class Cliente(models.Model):
    ESTADO_CIVIL = [
        ('SOL','SOLTEIRO'),
        ('CAS','CASADO'),
        ('DIV', 'DIVORCIADO'),
        ('VIU', 'VIUVO')

    ]
    nome = models.CharField(max_length=50)
    cpf = models.CharField(max_length=14)
    data_nascimento = models.DateField()
    email = models.EmailField(max_length=100, unique=True )
    endereco = models.CharField(max_length=250, null=True, verbose_name= 'Endereço')
    nro = models.IntegerField(null=True)
    bairro = models.CharField(max_length=50, null=True)
    cidade = models.CharField(max_length=50, null=True)
    cep = models.CharField(max_length=9, null=True)
    matricula = models.IntegerField()
    renda_mensal = models.DecimalField(max_digits=10, decimal_places=2)
    Ativo = models.BooleanField(verbose_name='Usario Ativo')
    estado_civil = models.CharField(max_length=3, choices=ESTADO_CIVIL, null= True)
    profissao = models.ForeignKey(Profissoes, on_delete=models.SET_NULL, null=True, verbose_name='Profissão')

    Interesse = models.ManyToManyField(Interesse)

    def __str__(self):
        return self.nome
    
class Telefone (models.Model):
    ddd = models.CharField(max_length=2)
    numero = models.CharField(max_length=10)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)

    def __str__(self):
        return f'({self.ddd}) {self.numero}'
    

CadastroCliente/views.py
from django.shortcuts import render

from CadastroCliente.models import Cliente, Profissoes, Telefone

# Create your views here.
def index (request):
    meu_nome = 'Ciclano da Silva'
    lista_frutas = ['Laranja', 'Maça', 'Banana']
    context = {

        'nome': meu_nome,
        'frutas': lista_frutas

    }
    return render(request, 'index.html', context)

def listar_cliente(request):
    #busca todos os clientes cadastrador na tabela 
    lista_clientes = Cliente.objects.all()
    # o dicionario (variavel) context é que vai mandar pro
    lista_profissoes = Profissoes.objects.all()
    context = {

        "clientes": lista_clientes,
        "profissoes": lista_profissoes
    }


    return render(request, 'lista_clientes.html', context)

def listar_profissoes(request):
    lista_profissoes = Profissoes.objects.all()
    context = {

        "profissoes": lista_profissoes
    }
    return render(request, 'lista_profissoes.html', context)

def detalhar_cliente(request, id):
    cliente = Cliente.objects.get(id = id)
    telefones = Telefone.objects.filter(cliente_id = id)

    context = {
        "cliente" : cliente,
        "telefones" : telefones
    }
    return render (request, "cliente_detalhes.html", context)

CadastroCliente/templates/cliente_detalhes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{cliente.nome}}</title>
</head>
<body>
    
    <h1> {{cliente.nome}}</h1>

    <table border="1">
        <tr>
            <td>Nome:</td>
            <td>{{cliente.nome}}</td>
        </tr>
        <tr>
            <td>Data de nascimento</td>
            <td>{{cliente.data_nascimento| date:"d/m/Y"}}</td>
        <tr>
                <td>Endereço:</td>
                <td>{{cliente.endereco}}, {{cliente.nro}} - {{cliente.bairro}} - {{cliente.cidade}}</td>
        </tr>
        </tr>
        <tr>
            <td>Cpf:</td>
            <td>{{ cliente.cpf}}</td>
        </tr>
        <tr>
            <td>E-mail:</td>
            <td>{{ cliente.email }}</td>
        </tr>
        <tr>
            <td>Matricula:</td>
            <td>{{ cliente.matricula }}</td>
        </tr>
        <tr>
            <td>Estado Civil:</td>
            <td>{{ cliente.get_estado_civil_display }}</td>
        </tr>
        <tr>
            <td>Profissao:</td>
            <td>{{ cliente.profissao }}</td>

        </tr>
        <tr>
            <td>Interesses:</td>
            <td>{{ cliente.Interesse.all|join:", " }}</td>
        </tr>
        <tr>
            <td>Telefones:</td>
            <td>{% for tel in telefones %}
                    ({{ tel.ddd }}) {{tel.numero}} <br>
                {% endfor %}
            </td>
        </tr>
    </table>

</body>
</html>

CadastroCliente/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css"
    href="{% static '/css/estilos.css' %}">
</head>
<body>
    <!-- Em Html -->
    <!-- <img src="../static/img/Logo_senac.jpg" > -->

    <!-- no djando -->
    <img src="{% static '/img/Logo_senac.jpg' %}">

<h1>{{ nome }}</h1>
<h2>{{ nome }}</h2>
<h3>{{ nome }}</h3>
<h4>{{ nome }}</h4>
<h5>{{ nome }}</h5>
<h6 class = "TextoLaranja">{{ nome }}</h6>

<ul>

    {% for frutas in frutas %}
    <li> {{frutas}} </li>
    {% endfor %}
</ul>



</body>
</html>

CadastroCliente/templates/lista_clientes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>clientes</title>
</head>
<body>

    <h1>Clientes Senac - SMP</h1>

    <ul>
        {% for x in clientes %}
        <li><a href="/cliente/{{ x.id }}">{{ x.nome }}</a>  - {{x.data_nascimento}} </li>
        {% endfor %}
    </ul>

    <h1>Profissoes Senac - SMP</h1>
        {% for x in profissoes %}
        <li> {{ x }} </li>
        {% endfor %}

</body>
</html>

CadastroCliente/templates/lista_profissoes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profissoes</title>
</head>
<body>
    
    <h1>Profissoes Senac - SMP</h1>

    <ul>
        {% for x in profissoes %}
        <li> {{ x }} </li>
        {% endfor %}
    </ul>

</body>
</html>